apiVersion: v1
kind: Service
metadata:
  name: {{ include "apartment-chart.fullname" . }}-backend-service
  labels:
    app: {{ .Chart.Name }}-backend
spec:
  type: {{ .Values.backend.service.type }}
  selector:
    app: {{ .Chart.Name }}-backend
  ports:
    - protocol: TCP
      port: {{ .Values.backend.service.port }}
      targetPort: {{ .Values.backend.service.targetPort }}
