apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "apartment-chart.fullname" . }}-frontend-config
  labels:
    app: {{ .Chart.Name }}-frontend
data:
  VITE_API_URL: "{{ .Values.frontend.env.apiUrl }}"
