apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "apartment-chart.fullname" . }}-frontend
  labels:
    app: {{ include "apartment-chart.name" . }}-frontend
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "apartment-chart.name" . }}-frontend
  template:
    metadata:
      labels:
        app: {{ include "apartment-chart.name" . }}-frontend
    spec:
      imagePullSecrets:
        - name: dockerhub-secret
      containers:
        - name: frontend
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.frontend.service.port }}
          env:
            - name: VITE_API_URL
              value: "{{ .Values.frontend.env.apiUrl }}"
