apiVersion: v1
kind: Service
metadata:
  name: {{ include "apartment-chart.fullname" . }}-frontend-service
  labels:
    app: {{ .Chart.Name }}-frontend
spec:
  type: {{ .Values.frontend.service.type | default "ClusterIP" }}
  selector:
    app: {{ .Chart.Name }}-frontend
  ports:
    - protocol: TCP
      port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.service.targetPort | default .Values.frontend.service.port }}
